=== politecnico2022-2/xml-primer-trabajo/HechosHistoricos.dtd
<!ELEMENT HechosHistoricos (HechoHistorico)+>
        <!ATTLIST HechoHistorico descripcion CDATA #REQUIRED>
        <!ELEMENT HechoHistorico (Fecha, Epoca?, PersonajeDestacado*)?>
        <!ELEMENT FormatoFecha (Dia, Mes, Año)>
        <!ELEMENT Epoca EMPTY>
        <!ELEMENT PersonajeDestacado ANY>
        <!ELEMENT Nombre (#PCDATA)>
        <!ELEMENT FechaNacimiento (#PCDATA)>
        <!ELEMENT Fecha (#PCDATA | FormatoFecha)*>
        <!ELEMENT Dia (#PCDATA)>
        <!ELEMENT Mes (#PCDATA)>
        <!ELEMENT Año (#PCDATA)>

=== politecnico2022-2/xml-primer-trabajo/XMLFileArchive.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE HechosHistoricos SYSTEM "HechosHistoricos.dtd">
<HechosHistoricos>
    <HechoHistorico descripcion="">
        <Fecha>
            <FormatoFecha>
                <Dia></Dia>
                <Mes></Mes>
                <A単o></A単o>
            </FormatoFecha>
        </Fecha>
        <Epoca/>
        <PersonajeDestacado>
            Test persona <Nombre></Nombre> y fecha de nacimiento: <FechaNacimiento></FechaNacimiento>
        </PersonajeDestacado>
    </HechoHistorico>

    <HechoHistorico descripcion="">
        <Fecha>
            <FormatoFecha>
                <Dia></Dia>
                <Mes></Mes>
                <A単o></A単o>
            </FormatoFecha>
        </Fecha>
        <Epoca/>
        <PersonajeDestacado>
            Test persona <Nombre></Nombre> y fecha de nacimiento: <FechaNacimiento></FechaNacimiento>
        </PersonajeDestacado>
    </HechoHistorico>
</HechosHistoricos>
